// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVDr_ZEYM0G-MXk1cWOc8QyACtjrGRz9k',
    appId: '1:833051621278:web:da21644cb965485197888f',
    messagingSenderId: '833051621278',
    projectId: 'test-sms-511ae',
    authDomain: 'test-sms-511ae.firebaseapp.com',
    storageBucket: 'test-sms-511ae.appspot.com',
    measurementId: 'G-G657NEFSEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4W8QU0d2LsP3sYgsboglgPfCaVoFLYN0',
    appId: '1:833051621278:android:5dda57550c9de5bd97888f',
    messagingSenderId: '833051621278',
    projectId: 'test-sms-511ae',
    storageBucket: 'test-sms-511ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK0BfNfTTR-oKemvgxrD5mXLTAUMWA-UM',
    appId: '1:833051621278:ios:0aa25567e1c6817097888f',
    messagingSenderId: '833051621278',
    projectId: 'test-sms-511ae',
    storageBucket: 'test-sms-511ae.appspot.com',
    iosClientId: '833051621278-4tc3klvk44qvmk1oljpsvdp76flgch0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK0BfNfTTR-oKemvgxrD5mXLTAUMWA-UM',
    appId: '1:833051621278:ios:0aa25567e1c6817097888f',
    messagingSenderId: '833051621278',
    projectId: 'test-sms-511ae',
    storageBucket: 'test-sms-511ae.appspot.com',
    iosClientId: '833051621278-4tc3klvk44qvmk1oljpsvdp76flgch0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
